// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FeedbackFormController from "./feedback_form_controller"
application.register("feedback-form", FeedbackFormController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
